# -*- coding: utf-8 -*-
"""Bakery XGboost regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjztMtUz3lH-l2hTkNOTfouN7sv8Ar3q
"""

#IMPORTS

import os
import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import holidays  # pip install holidays

from xgboost import XGBRegressor
import xgboost as xgb


from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')
  df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))

print("CSV file loaded into a DataFrame named 'df'.")
print(df.head())

#show me all columns
pd.set_option('display.max_columns', None)
df.info()

"""# Task
Perform data inspection, cleaning, and visual exploration on the bakery dataset from "Bakery sales.csv" by converting the 'date' column to datetime, formatting 'unit_price' as a numeric type, and visualizing top-selling articles and sales trends.

## Data Inspection

### Subtask:
Examine data types, missing values, and summary statistics to understand the structure of the bakery dataset.
"""

print('--- Data Info ---')
df.info()

print('\n--- Summary Statistics (Numerical) ---')
display(df.describe())

print('\n--- Summary Statistics (Categorical) ---')
display(df.describe(include='O'))

print('\n--- Null Values per Column ---')
print(df.isnull().sum())

print('\n--- Duplicate Rows ---')
print(f'Total duplicates: {df.duplicated().sum()}')

"""## Data Cleaning

### Subtask:
Clean the 'unit_price' column by removing currency symbols and converting it to a numeric format, and convert the 'date' column to datetime objects.

"""

# Clean unit_price: remove symbols, replace comma with dot
# Convert unit_price to float
# Combine date and time to create a single datetime column
# Drop redundant Unnamed: 0 column

df['unit_price'] = df['unit_price'].str.replace('€', '', regex=False).str.replace(',', '.', regex=False).str.strip()
df['unit_price'] = df['unit_price'].astype(float)

# Combining date and time strings then converting to datetime
df['date'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str))

if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)

# Print checks
print("--- Updated Data Types ---")
print(df.dtypes)
print("\n--- First 5 Rows of Cleaned Data ---")
display(df.head())

print("Data cleaning for 'unit_price', combined 'date', and column removal completed.")

#show the cleaned data
df.head()

skew_quantity = df['Quantity'].skew()
skew_price = df['unit_price'].skew()

print(f"Skewness for Quantity: {skew_quantity:.2f}")
print(f"Skewness for Unit Price: {skew_price:.2f}")

plt.figure(figsize=(12, 5))

# Plot for Quantity
plt.subplot(1, 2, 1)
sns.histplot(df['Quantity'], kde=True, color='skyblue')
plt.title(f'Quantity Distribution (Skew: {skew_quantity:.2f})')

# Plot for Unit Price
plt.subplot(1, 2, 2)
sns.histplot(df['unit_price'], kde=True, color='salmon')
plt.title(f'Unit Price Distribution (Skew: {skew_price:.2f})')

plt.tight_layout()
plt.show()

# Skew check per article
# Some articles may be skewed while others are not.
article_skew = df.groupby('article')['Quantity'].skew().sort_values(ascending=False)
print("\n--- Skewness per Article ---")
print(article_skew)

pearson_corr = df['unit_price'].corr(df['Quantity'], method='pearson')
spearman_corr = df['unit_price'].corr(df['Quantity'], method='spearman')

print(f"Pearson Correlation: {pearson_corr:.4f}")
print(f"Spearman Correlation: {spearman_corr:.4f}")

# Scatter
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='unit_price', y='Quantity', alpha=0.5)
sns.regplot(data=df, x='unit_price', y='Quantity', scatter=False, color='red')

plt.title('Correlation: Unit Price vs Quantity Sold')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# Checking if the relationship is power-law based (log-log)
# This often "un-skews" the visualization for better insight
df['log_price'] = np.log1p(df['unit_price'])
df['log_qty'] = np.log1p(df['Quantity'])

log_corr = df['log_price'].corr(df['log_qty'])
print(f"Log-Transformed Correlation: {log_corr:.4f}")

"""I hate timeseries outliers"""

df_clean = df[(df['Quantity'] > 0) & (df['unit_price'] > 0)].copy()

# log1p transformation
# log1p is log(1+x), which is safer for small values
df_clean['log_qty'] = np.log1p(df_clean['Quantity'])
df_clean['log_price'] = np.log1p(df_clean['unit_price'])

# recheck correlation with positive only data
new_corr = df_clean['log_price'].corr(df_clean['log_qty'])
print(f"Cleaned Log-Transformed Correlation: {new_corr:.4f}")

# Handle per-article Skewness (Clip Outliers)
# For SEIGLE (skew 27), we clip values above the 99th percentile
# to prevent the model from obsessing over one-off huge orders.
df_clean['Quantity'] = df_clean.groupby('article')['Quantity'].transform(
    lambda x: x.clip(upper=x.quantile(0.99))
)

df_clean['day_of_week'] = df_clean['date'].dt.dayofweek  # 0=Monday, 6=Sunday
df_clean['is_weekend'] = df_clean['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)
df_clean['month'] = df_clean['date'].dt.month
df_clean['hour'] = df_clean['date'].dt.hour

# Im trying to handle Extreme Skewness per Article (The 'Seigle' Problem)
# trying to predict extreme, one-off spikes.
df_clean['Quantity_clipped'] = df_clean.groupby('article')['Quantity'].transform(
    lambda x: x.clip(upper=x.quantile(0.99))
)

# check prints
print("Correlation with Quantity:")
print(f"Day of Week: {df_clean['day_of_week'].corr(df_clean['Quantity']):.4f}")
print(f"Is Weekend: {df_clean['is_weekend'].corr(df_clean['Quantity']):.4f}")
print(f"Hour: {df_clean['hour'].corr(df_clean['Quantity']):.4f}")

print("\n--- New Feature Set ---")
print(df_clean[['date', 'article', 'Quantity_clipped', 'day_of_week', 'is_weekend', 'hour']].head())

df_daily = df_clean.groupby([df_clean['date'].dt.date, 'article']).agg({
    'Quantity': 'sum',
    'unit_price': 'mean',
    'day_of_week': 'first',
    'is_weekend': 'first',
    'month': 'first'
}).reset_index()

# Rename the column back for consistency
df_daily.rename(columns={'date': 'date_dt'}, inplace=True)
df_daily['date_dt'] = pd.to_datetime(df_daily['date_dt'])

# --- FRENCH HOLIDAY FLAG ---
fr_holidays = holidays.France()
df_daily['is_holiday'] = df_daily['date_dt'].apply(lambda d: int(d in fr_holidays))

# --- RE-ENCODE ARTICLES ON NEW DATAFRAME ---
le = LabelEncoder()
df_daily['article_encoded'] = le.fit_transform(df_daily['article'])

# --- LAG FEATURES (per article) ---
df_daily.sort_values(['article', 'date_dt'], inplace=True)
df_daily['sales_1_day_ago']   = df_daily.groupby('article')['Quantity'].shift(1)
df_daily['sales_7_days_ago']  = df_daily.groupby('article')['Quantity'].shift(7)
df_daily['rolling_7_day_avg'] = (
    df_daily.groupby('article')['Quantity']
    .transform(lambda x: x.shift(1).rolling(7, min_periods=1).mean())
)

# Drop rows where the first lag is NaN (very first day per article)
df_daily.dropna(subset=['sales_1_day_ago'], inplace=True)

print(f"\n--- Lag Feature Sample ---")
print(df_daily[['date_dt','article','Quantity','sales_1_day_ago','sales_7_days_ago','rolling_7_day_avg','is_holiday']].head(10))

# --- REDEFINE TRAINING DATA ---
# Feature list now includes lag features and holiday flag
features = [
    'article_encoded', 'unit_price', 'day_of_week', 'is_weekend', 'month',
    'sales_1_day_ago', 'sales_7_days_ago', 'rolling_7_day_avg', 'is_holiday'
]
X = df_daily[features]

# --- LOG-TRANSFORM TARGET ---
# Training on log1p(Quantity) helps the model handle heteroscedasticity
y = np.log1p(df_daily['Quantity'])

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape}")
print(f"Testing set size: {X_test.shape}")
print("\n--- Encoded Feature Sample ---")
print(X_train.head())

"""# XGBoost Model Training

"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error

# Init xgboost regressor
model = xgb.XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

model.fit(X_train, y_train)

# Predict in log-space then inverse-transform back to original scale
y_pred_log = model.predict(X_test)
y_pred = np.expm1(y_pred_log)
y_test_actual = np.expm1(y_test)   # original-scale actuals for metrics

# evals -_-
mae = mean_absolute_error(y_test_actual, y_pred)
rmse = root_mean_squared_error(y_test_actual, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

"""This means that the model can have unpredictable moment (especially with the Seigle sales). This might be due to extreme spikes/random sales."""

plt.figure(figsize=(10, 6))
xgb.plot_importance(model, importance_type='weight', ax=plt.gca(), color='skyblue')
plt.title('Which features matter most for Bakery Sales?')
plt.show()

#taking article to test

target_article = 'BAGUETTE'
article_id = le.transform([target_article])[0]
avg_price = df_clean[df_clean['article'] == target_article]['unit_price'].mean()

# --- HELPER: iterative forecast that seeds lag features day-by-day ---
def iterative_forecast(model, features, article_id, avg_price, start_date, num_days, history_df, article_name):
    """
    Forecast `num_days` into the future starting from `start_date`.
    Uses `history_df` (daily data for this article) to seed lag features,
    then walks forward one day at a time, feeding each prediction back
    as the next day's sales_1_day_ago.
    Returns a DataFrame with date + Predicted_Sales columns.
    """
    # Get the last known sales for this article (sorted by date)
    art_hist = history_df[history_df['article'] == article_name].sort_values('date_dt')
    recent_sales = list(art_hist['Quantity'].tail(7).values)  # last 7 days

    rows = []
    for i in range(num_days):
        d = start_date + pd.Timedelta(days=i)
        s1  = recent_sales[-1] if len(recent_sales) >= 1 else 0
        s7  = recent_sales[-7] if len(recent_sales) >= 7 else (recent_sales[0] if recent_sales else 0)
        r7  = float(np.mean(recent_sales[-7:])) if recent_sales else 0.0
        hol = int(d in fr_holidays)

        row = {
            'article_encoded': article_id,
            'unit_price':      avg_price,
            'day_of_week':     d.dayofweek,
            'is_weekend':      int(d.dayofweek >= 5),
            'month':           d.month,
            'sales_1_day_ago': s1,
            'sales_7_days_ago':s7,
            'rolling_7_day_avg': r7,
            'is_holiday':      hol,
        }
        pred_log = model.predict(pd.DataFrame([row])[features])[0]
        pred_qty = np.expm1(pred_log)
        pred_qty = max(pred_qty, 0)  # clamp negatives

        rows.append({'date': d, 'Predicted_Sales': pred_qty})
        recent_sales.append(pred_qty)  # feed prediction back as history

    return pd.DataFrame(rows)

#create a 7-day future forecast (Starting tomorrow)
forecast_df = iterative_forecast(
    model, features, article_id, avg_price,
    start_date=pd.Timestamp.now().floor('D') + pd.Timedelta(days=1),
    num_days=7,
    history_df=df_daily,
    article_name=target_article
)

print(f"--- 7-Day Forecast for {target_article} (Daily Total) ---")
print(forecast_df[['date', 'Predicted_Sales']])

#Data cutoff date
last_date = df_clean['date'].max().floor('D')
print(f"Data Cutoff Date: {last_date}")

#Forecasting windows
windows = {'7-Day': 7, '30-Day': 30}
rmse_buffer = rmse  # dynamically use the actual RMSE from training

#loop
for article_name in le.classes_[:3]:
    article_id = le.transform([article_name])[0]
    avg_price = df_clean[df_clean['article'] == article_name]['unit_price'].mean()

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))

    for ax, (label, days) in zip([ax1, ax2], windows.items()):
        # Iterative forecast with lag features
        fcast = iterative_forecast(
            model, features, article_id, avg_price,
            start_date=last_date + pd.Timedelta(days=1),
            num_days=days,
            history_df=df_daily,
            article_name=article_name
        )
        future_range = fcast['date']
        preds = fcast['Predicted_Sales'].values

        #plot
        ax.plot(future_range, preds, marker='o' if days==7 else None, color='navy', label='Forecast')
        ax.fill_between(future_range,
                         np.maximum(0, preds - rmse_buffer),
                         preds + rmse_buffer,
                         color='blue', alpha=0.1, label='Uncertainty')

        ax.set_title(f"{label} Forecast: {article_name}")
        ax.tick_params(axis='x', rotation=45)
        ax.grid(True, linestyle='--', alpha=0.5)
        ax.legend()

    plt.tight_layout()
    plt.show()

"""# Stock recommendation

The "Safety Stock" Approach

Because the model has an RMSE of 0.9095, there is a statistical "error margin." To avoid running out of stock (Stockout), we apply a Ceiling Function to the upper bound of the prediction.

Baseline Prediction: $1.4$ units (The mathematical average).

Rounding: $1$ unit (50% chance of a stockout).

Safety Recommendation: $\lceil 1.4 + \text{RMSE} \rceil = \lceil
2.3095 \rceil = 3$ units.
"""

# Compute Coefficient of Variation (CV) to identify high volatility articles
article_stats = df_daily.groupby('article')['Quantity'].agg(['mean', 'std']).fillna(0)
article_stats['CV'] = np.where(article_stats['mean'] > 0, article_stats['std'] / article_stats['mean'], 0)

# Flag articles where std dev > mean (high volatility / high uncertainty)
high_uncertainty_articles = set(article_stats[article_stats['CV'] > 1.0].index)

rmse_buffer = rmse  # base model RMSE
last_date = df_clean['date'].max().floor('D')
forecast_days = 7

recommendations = []

for article_name in le.classes_:
    article_id = le.transform([article_name])[0]
    avg_price = df_clean[df_clean['article'] == article_name]['unit_price'].mean()

    # Iterative forecast with lag features
    fcast = iterative_forecast(
        model, features, article_id, avg_price,
        start_date=last_date + pd.Timedelta(days=1),
        num_days=forecast_days,
        history_df=df_daily,
        article_name=article_name
    )

    is_high_uncertainty = article_name in high_uncertainty_articles
    
    # Apply a larger safety buffer (1.5x RMSE) for highly volatile items
    dynamic_buffer = rmse_buffer * 1.5 if is_high_uncertainty else rmse_buffer

    # Ceiling(Prediction + dynamic_buffer)
    for _, row in fcast.iterrows():
        recommendations.append({
            'Date': row['date'].strftime('%Y-%m-%d'),
            'Day': row['date'].strftime('%A'),
            'Article': article_name,
            'Recommended_Stock': math.ceil(row['Predicted_Sales'] + dynamic_buffer),
            'High_Uncertainty': is_high_uncertainty
        })

# Create Final Report df
reco_df = pd.DataFrame(recommendations)

# Display recommendations for a specific article
print("--- Safe Stock Recommendations for the Next 7 Days ---")
print(reco_df[reco_df['Article'] == 'BAGUETTE'].head(7))

"""Imma test that prediction and then try simulating from a past time point to check if the prediction + recommendations works Ehe"""

# Pick a random starting point from the past
# Ensure the window doesn't go beyond the dataset's end
min_date = df_clean['date'].min()
max_date = df_clean['date'].max() - pd.Timedelta(days=7)
random_start = pd.to_datetime(np.random.choice(pd.date_range(min_date, max_date)))

print(f"Testing Strategy on Week Starting: {random_start.date()}")

# Extract Actual Data for that week
actual_week = df_clean[(df_clean['date'] >= random_start) &
                       (df_clean['date'] < random_start + pd.Timedelta(days=7))].copy()

# Generate Recommendations for that specific week (using iterative forecast)
test_recos = []
base_rmse_buffer = rmse  # use actual model RMSE

# Build a history_df limited to data BEFORE the random_start (no data leakage)
history_before = df_daily[df_daily['date_dt'] < pd.to_datetime(random_start)]

for article_name in actual_week['article'].unique():
    article_id = le.transform([article_name])[0]
    avg_price = df_clean[df_clean['article'] == article_name]['unit_price'].mean()

    fcast = iterative_forecast(
        model, features, article_id, avg_price,
        start_date=pd.to_datetime(random_start),
        num_days=7,
        history_df=history_before,
        article_name=article_name
    )

    is_high_uncertainty = article_name in high_uncertainty_articles
    dynamic_buffer = base_rmse_buffer * 1.5 if is_high_uncertainty else base_rmse_buffer

    for _, row in fcast.iterrows():
        test_recos.append({
            'date_key': row['date'].date(),
            'article': article_name,
            'Recommended_Stock': math.ceil(row['Predicted_Sales'] + dynamic_buffer)
        })

reco_comparison = pd.DataFrame(test_recos)
actual_daily = actual_week.groupby([actual_week['date'].dt.date, 'article'])['Quantity'].sum().reset_index()
actual_daily.columns = ['date_key', 'article', 'Actual_Quantity']

#Combine both dataframes
comparison_df = pd.merge(reco_comparison, actual_daily, on=['date_key', 'article'], how='left').fillna(0)

#Calculate Performance Metrics
comparison_df['Stockout'] = comparison_df['Actual_Quantity'] > comparison_df['Recommended_Stock']
comparison_df['Buffer_Remaining'] = comparison_df['Recommended_Stock'] - comparison_df['Actual_Quantity']

print("\n--- Performance Summary ---")
stockout_rate = comparison_df['Stockout'].mean() * 100
print(f"Stockout Rate (How often you ran out): {stockout_rate:.2f}%")
print(f"Average Extra Units per Item: {comparison_df['Buffer_Remaining'].mean():.2f}")

# Show top 5 items for visual check
print("\n--- Sample Comparison (First 5 Rows) ---")
print(comparison_df[['date_key', 'article', 'Recommended_Stock', 'Actual_Quantity', 'Stockout']].head())

from sklearn.metrics import r2_score

# Calculate R-squared score (on original scale)
r2 = r2_score(y_test_actual, y_pred)

# Calculate Mean Absolute Percentage Error (MAPE) - excluding zero actuals to avoid division by zero
mask = y_test_actual != 0
mape = np.mean(np.abs((y_test_actual[mask] - y_pred[mask]) / y_test_actual[mask])) * 100

# Weighted MAPE — weights each error by the item's actual volume,
# so high-volume items (Baguettes) matter more than slow-movers selling 1-2 units.
# Formula: sum(|actual - pred|) / sum(actual) * 100
wmape = np.sum(np.abs(y_test_actual[mask] - y_pred[mask])) / np.sum(y_test_actual[mask]) * 100

print(f"--- Accuracy Metrics ---")
print(f"R-squared Score: {r2:.4f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
print(f"Weighted MAPE (WMAPE): {wmape:.2f}%")

# Comparison visualization (original scale)
plt.figure(figsize=(10, 6))

# Map y_test back to article names to determine color
test_article_names = le.inverse_transform(X_test['article_encoded'])
is_high_unc = np.array([name in high_uncertainty_articles for name in test_article_names])

# Scatter plot for normal articles
plt.scatter(
    y_test_actual[~is_high_unc], 
    y_pred[~is_high_unc], 
    alpha=0.3, color='purple', label='Normal Volatility'
)

# Scatter plot for high uncertainty articles
plt.scatter(
    y_test_actual[is_high_unc], 
    y_pred[is_high_unc], 
    alpha=0.5, color='darkorange', label='High Volatility (CV > 1.0)'
)

# Ideal prediction line
plt.plot([y_test_actual.min(), y_test_actual.max()], 
         [y_test_actual.min(), y_test_actual.max()], 
         'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Quantity')
plt.ylabel('Predicted Quantity')
plt.title('Actual vs Predicted Bakery Sales (Log-Target Model)')
plt.legend()
plt.show()